name: helm3
version: '3.12.0'
summary: The Kubernetes package manager
description: |
  Helm is a tool for managing Kubernetes
  charts. Charts are packages of
  pre-configured Kubernetes resources.
base: core18
grade: stable
confinement: strict

apps:
  helm3:
    command: helm3
    plugs: [home, network, network-bind]

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

parts:
  helm3:
    plugin: dump
    source: .
    override-build: |
      apt install curl tar -y
      curl -Lo helm.tar.gz https://get.helm.sh/helm-v$SNAPCRAFT_PROJECT_VERSION-linux-amd64.tar.gz
      tar xzf helm.tar.gz
      mkdir -p /build/parts/helm3/install/bin
      mv linux-amd64/helm /build/parts/helm3/install/bin/helm3
